import Head from "next/head";
import Header from "@/components/Header";
import AboutSection from "@/components/AboutSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Natours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <main>
          <AboutSection />
        </main>
      </main>
    </>
  );
}
